"""feat-016 chunk 3: the grounded Agent loop end to end (hermetic).

Drives a real ``agentforge.Agent`` over the real read-only ckg tools with a
scripted ``MockLLMClient`` (no creds, no network): the mock requests a tool call
(exercising the tool boundary) then emits the final doc, which is verified,
written under ``output_root``, and recorded in the manifest.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from pathlib import Path

import pytest
from agentforge.testing import MockLLMClient

from agentforge_graph.config import DocGenConfig
from agentforge_graph.docgen import DocGenerator, get_recipe
from agentforge_graph.docgen.errors import DocgenError, UngroundedError
from agentforge_graph.docgen.types import STATUS_DRAFT, DocTarget, DocType
from agentforge_graph.ingest import CodeGraph

_SRC = """\
class Repo:
    def save(self):
        return validate()


def validate():
    return True
"""


@pytest.fixture
async def indexed(tmp_path: Path) -> AsyncIterator[tuple[CodeGraph, Path]]:
    (tmp_path / "app.py").write_text(_SRC)
    cg = await CodeGraph.index(repo_path=tmp_path)
    yield cg, tmp_path
    await cg.close()


async def _seed_id(cg: CodeGraph) -> str:
    pack = await get_recipe(DocType.ARCHITECTURE).seed(cg, DocTarget(type=DocType.ARCHITECTURE))
    assert pack.facts
    return pack.facts[0].ref.id


def _script(final_doc: str) -> MockLLMClient:
    # turn 1: request a (deterministic, embedding-free) tool call; turn 2: the doc.
    return MockLLMClient.from_script(
        [
            {
                "text": "Let me look at the repo map.",
                "tool_calls": [{"name": "ckg_repo_map", "args": {"budget_tokens": 400}}],
            },
            {"text": final_doc, "stop_reason": "end_turn"},
        ]
    )


async def test_generate_writes_grounded_draft(indexed: tuple[CodeGraph, Path]) -> None:
    cg, repo = indexed
    sid = await _seed_id(cg)
    final = (
        "## Overview\n\nThe system centers on this symbol [^f1].\n\n"
        f"## References\n\n[^f1]: {sid}\n"
    )
    gen = DocGenerator(cg, DocGenConfig(), repo_path=repo, model=_script(final))

    art = await gen.generate(DocTarget(type=DocType.ARCHITECTURE))

    assert art.type is DocType.ARCHITECTURE
    assert art.status == STATUS_DRAFT
    assert art.path == "docs/_generated/architecture.md"
    assert {f.marker for f in art.footnotes} == {"f1"}
    assert sid in art.source_ids

    written = (repo / art.path).read_text()
    assert "Generated by CKG docgen" in written  # provenance header
    assert "[^f1]" in written
    assert "do not edit by hand" in written

    # recorded in the sidecar manifest as a draft
    from agentforge_graph.docgen import Manifest

    m = Manifest(repo / "docs/_generated")
    assert m.get(art.path) is not None
    assert m.get(art.path).status == STATUS_DRAFT  # type: ignore[union-attr]


async def test_generate_rejects_fabricated_citation(indexed: tuple[CodeGraph, Path]) -> None:
    cg, repo = indexed
    # cite an id the seed/tools never produced → pruned; the sole section is then
    # ungrounded under require_citations → UngroundedError
    bad = "## Overview\n\nClaim [^f1].\n\n## References\n\n[^f1]: ckg py repo ghost.py Ghost#\n"
    gen = DocGenerator(cg, DocGenConfig(), repo_path=repo, model=_script(bad))
    with pytest.raises(UngroundedError):
        await gen.generate(DocTarget(type=DocType.ARCHITECTURE))


async def test_generate_budget_trip_raises(indexed: tuple[CodeGraph, Path]) -> None:
    cg, repo = indexed
    cfg = DocGenConfig(budget_usd=0.0)  # trips before the first LLM call
    gen = DocGenerator(cg, cfg, repo_path=repo, model=MockLLMClient.deterministic("x"))
    with pytest.raises(DocgenError, match="budget"):
        await gen.generate(DocTarget(type=DocType.ARCHITECTURE))
