"""``DocGenerator`` (feat-016) — orchestrates one grounded doc: seed → compose →
verify → emit draft + manifest entry.

Chunk 3 lands the ``generate`` path (a single doc, end to end); ``update`` /
``list`` / ``diff`` / ``promote`` / ``sync`` land in later chunks.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

from .citations import verify_citations
from .manifest import Manifest, content_sha
from .recipes import get_recipe
from .runner import AgentDocRunner
from .templates.base import get_template
from .types import DOC_LANG_VERSION, STATUS_DRAFT, DocArtifact, DocTarget, DocType

if TYPE_CHECKING:
    from agentforge_core.contracts.llm import LLMClient

    from agentforge_graph.config import ConfigSource, DocGenConfig
    from agentforge_graph.ingest import CodeGraph


def _slug(scope: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "-", scope).strip("-") or "root"


class DocGenerator:
    """Generates grounded docs for one repository/config."""

    def __init__(
        self,
        cg: CodeGraph,
        cfg: DocGenConfig,
        *,
        repo_path: str | Path,
        config: ConfigSource = None,
        model: str | LLMClient | None = None,
    ) -> None:
        self._cg = cg
        self._cfg = cfg
        self._repo_path = Path(repo_path)
        self._runner = AgentDocRunner(cfg, repo_path=str(repo_path), config=config, model=model)

    async def generate(self, target: DocTarget) -> DocArtifact:
        """Generate one doc: seed the pack, run the grounded Agent loop, verify
        citations, write the draft under ``output_root``, and record it."""
        recipe = get_recipe(target.type)
        pack = await recipe.seed(self._cg, target)
        template = get_template(target.type)

        body, prov = await self._runner.compose(pack, template)
        verified = verify_citations(body, prov, require_citations=self._cfg.require_citations)

        commit = self._git_commit()
        rel = self._doc_relpath(target)
        full = self._stamp(verified.body, target, commit)
        abs_path = self._repo_path / rel
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(full)

        artifact = DocArtifact(
            type=target.type,
            path=rel,
            status=STATUS_DRAFT,
            synced_commit=commit,
            doc_lang_version=DOC_LANG_VERSION,
            source_ids=prov.source_ids(),
            footnotes=verified.footnotes,
            content_sha=content_sha(full),
        )
        self._manifest().upsert(artifact)
        return artifact

    # --- helpers -------------------------------------------------------------

    def _manifest(self) -> Manifest:
        return Manifest(self._repo_path / self._cfg.output_root)

    def _doc_relpath(self, target: DocTarget) -> str:
        root = self._cfg.output_root.rstrip("/")
        if target.type is DocType.COMPONENT and target.scope:
            return f"{root}/component/{_slug(target.scope)}.md"
        return f"{root}/{target.type.value}.md"

    def _stamp(self, body: str, target: DocTarget, commit: str) -> str:
        header = (
            "<!-- Generated by CKG docgen — do not edit by hand.\n"
            f"     type: {target.type.value} · synced @{commit or 'unknown'} · "
            f"doc_lang_version {DOC_LANG_VERSION} -->\n\n"
        )
        return header + body.strip() + "\n"

    def _git_commit(self) -> str:
        from agentforge_graph.ingest.codegraph import _git_commit

        return _git_commit(self._repo_path)
