"""Value types for grounded doc generation (feat-016).

Frozen dataclasses, ``core``-typed where they reference the graph. These are the
vocabulary the recipes / runner / citation verifier / manifest all speak:

- :class:`DocTarget` — *what* to document.
- :class:`GroundedFact` / :class:`GroundedPack` — the recipe **seed**: real graph
  facts (each carrying a :class:`SymbolRef`) handed to the Agent up front.
- :class:`ProvenanceSet` — everything the read-only tools surfaced during a run
  (seed ∪ tool results); the citation trust boundary and the staleness key.
- :class:`Footnote` — a verified citation (marker → :class:`SymbolRef`).
- :class:`DocArtifact` — the emitted draft + its metadata (what the manifest
  persists).

This module is pure data — no LLM, no I/O — so it is trivially unit-testable and
imports only ``core``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from agentforge_graph.core import NodeKind

#: The template + citation contract version. Bumped when the section skeletons or
#: the citation model change in a way that makes an existing doc worth
#: regenerating (mirrors feat-015's ``query_lang_version``). Stamped into every
#: manifest entry and reported by ``ckg_status``.
DOC_LANG_VERSION = "1.0"

#: Doc lifecycle states. A generated doc is a ``draft`` until a human promotes it.
STATUS_DRAFT = "draft"
STATUS_ACCEPTED = "accepted"


class DocType(StrEnum):
    """The four descriptive doc types feat-016 ships (Phase 1)."""

    AI_CONTEXT = "ai-context"  # CLAUDE.md / AGENTS.md
    ARCHITECTURE = "architecture"  # system overview
    COMPONENT = "component"  # per-module doc(s)
    DESIGN = "design"  # "how it works + why" for a subsystem


@dataclass(frozen=True)
class DocTarget:
    """What to document: a doc type + an optional scope (repo | package/path |
    subsystem | symbol id)."""

    type: DocType
    scope: str | None = None


@dataclass(frozen=True)
class SymbolRef:
    """A citable pointer into the graph — built from a ``core.models.Node`` or a
    ``retrieve.pack.ContextItem`` (both carry id/kind/name/path/span)."""

    id: str  # a SymbolID string
    kind: NodeKind
    name: str
    path: str | None = None
    span: tuple[int, int] | None = None


@dataclass(frozen=True)
class GroundedFact:
    """One seed fact: text phrased for the model + the symbol it cites + the
    provenance of the underlying graph fact (only ``>= parsed`` is ground
    truth)."""

    text: str
    ref: SymbolRef
    source: str  # a core.Source value ("parsed" | "resolved" | "llm" | "manual")


@dataclass(frozen=True)
class GroundedPack:
    """The recipe **seed** — high-value facts handed to the Agent up front. The
    Agent expands it by calling the read-only ckg toolset. ``notes`` is
    non-citable framing (recipe-level context)."""

    target: DocTarget
    facts: tuple[GroundedFact, ...] = ()
    notes: tuple[str, ...] = ()


@dataclass(frozen=True)
class ProvenanceSet:
    """Every ``SymbolRef`` the run grounded on — the seed refs plus every ref a
    read-only tool returned during composition. A footnote may cite a symbol only
    if it is ``contains``-ed here (the citation trust boundary), and its keys are
    the doc's staleness ``source_ids``."""

    refs: dict[str, SymbolRef] = field(default_factory=dict)

    def contains(self, symbol_id: str) -> bool:
        return symbol_id in self.refs

    def source_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self.refs))

    @classmethod
    def build(cls, *groups: dict[str, SymbolRef]) -> ProvenanceSet:
        """Union several ``{id: SymbolRef}`` maps (seed + captured tool results)
        into one set; earlier groups win on a key collision."""
        merged: dict[str, SymbolRef] = {}
        for group in reversed(groups):
            merged.update(group)
        return cls(refs=merged)


@dataclass(frozen=True)
class Footnote:
    """A verified citation: a footnote marker (e.g. ``"f3"``) → the symbol it
    resolves to. Present in a ``DocArtifact`` only after verification against the
    :class:`ProvenanceSet`."""

    marker: str
    ref: SymbolRef


@dataclass(frozen=True)
class DocArtifact:
    """A generated doc + its metadata (what the manifest persists). ``stale`` is
    *computed* (never serialized) — a doc is stale when a source symbol changed,
    the index moved past ``synced_commit``, or the ``doc_lang_version`` bumped."""

    type: DocType
    path: str  # repo-relative, under docgen.output_root
    status: str  # STATUS_DRAFT | STATUS_ACCEPTED
    synced_commit: str  # git commit the run was built from
    doc_lang_version: str
    source_ids: tuple[str, ...]  # ProvenanceSet keys — the staleness key
    footnotes: tuple[Footnote, ...] = ()
    content_sha: str = ""  # sha256 of the generated bytes (drift detection)
    stale: bool = False  # computed, not serialized

    @property
    def accepted(self) -> bool:
        return self.status == STATUS_ACCEPTED
