"""Provenance — attribution carried by every node and edge.

Every fact in the graph records where it came from, so an agent can
tell parsed ground truth from a heuristic resolution or an LLM guess,
and rank/filter accordingly. Enforced at construction so no
unattributed fact can exist. See ADR-0004.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, model_validator


class Source(StrEnum):
    """How a fact was derived, in decreasing reliability."""

    PARSED = "parsed"  # straight from the syntax tree
    RESOLVED = "resolved"  # upgraded via the import graph / resolver
    LLM = "llm"  # generated by a model (summaries, pattern tags, inferred links)
    MANUAL = "manual"  # human-asserted


class Provenance(BaseModel):
    """Attribution for a single node or edge."""

    model_config = ConfigDict(frozen=True)

    source: Source
    extractor: str  # producer name + version, e.g. "tree-sitter-python@0.23"
    commit: str = ""  # git sha the fact was derived at; "" if non-git / unstaged
    confidence: float = 1.0  # < 1.0 only meaningful for source=llm

    @model_validator(mode="after")
    def _check_confidence(self) -> Provenance:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be in [0.0, 1.0]")
        if self.source is not Source.LLM and self.confidence != 1.0:
            raise ValueError("confidence < 1.0 is only valid for source=llm")
        return self

    @classmethod
    def parsed(cls, extractor: str, commit: str = "") -> Provenance:
        return cls(source=Source.PARSED, extractor=extractor, commit=commit)

    @classmethod
    def resolved(cls, extractor: str, commit: str = "") -> Provenance:
        return cls(source=Source.RESOLVED, extractor=extractor, commit=commit)

    @classmethod
    def manual(cls, extractor: str, commit: str = "") -> Provenance:
        return cls(source=Source.MANUAL, extractor=extractor, commit=commit)

    @classmethod
    def llm(cls, extractor: str, confidence: float, commit: str = "") -> Provenance:
        return cls(
            source=Source.LLM,
            extractor=extractor,
            confidence=confidence,
            commit=commit,
        )
